<?php 
function tpl_1232078367_1_1_14navpostsht04eb5383c08601d1c59f39f6baefaeb6_loader( $tpl, $ctx ) {
$tpl = clone $tpl ;
$ctx = $tpl->getContext() ;
$glb = $tpl->getGlobalContext() ;
$_translator = $tpl->getTranslator() ;
?>
	
	<?php ob_start(); ?><div class="pagination">
	<!-- hook: nav_posts -->
		<span class="previous"><?php echo phptal_path($ctx->vanilla, 'nav_posts/next_posts_link', true) ?></span>
		<span class="next"><?php echo phptal_path($ctx->vanilla, 'nav_posts/previous_posts_link', true) ?></span>
	</div><?php $ctx->fillSlot("nav_posts", ob_get_clean()); ?>
	
<?php 
}

 ?><?php 
function tpl_1232078367_1_1_14navpostsht04eb5383c08601d1c59f39f6baefaeb6( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
$_translator = $tpl->getTranslator() ;
?>

<?php 
}

 ?><?php /* Generated by PHPTAL from /home/dynamicbt/www.dynamicbodytherapy.com/wp-content/themes/vanilla/blog-set/misc/nav-posts.html */; ?>