<?php 
function tpl_1232078367_1_1_14vanillautie067bf7864cb5de95f90ad4b00c8340f_vanilla_utility_4_col( $tpl, $ctx ) {
$tpl = clone $tpl ;
$ctx = $tpl->getContext() ;
$glb = $tpl->getGlobalContext() ;
$_translator = $tpl->getTranslator() ;
?>
		<div class="yui-g first">
			<div class="yui-u first">
				<?php if ($ctx->hasSlot("utility_1")): ; ?><?php echo $ctx->getSlot("utility_1") ?><?php else: ; ?><span></span><?php endif; ?>
			</div>
			<div class="yui-u">
				<?php if ($ctx->hasSlot("utility_2")): ; ?><?php echo $ctx->getSlot("utility_2") ?><?php else: ; ?><span></span><?php endif; ?>
			</div>
		</div>
		<div class="yui-g">
			<div class="yui-u first">
				<?php if ($ctx->hasSlot("utility_3")): ; ?><?php echo $ctx->getSlot("utility_3") ?><?php else: ; ?><span></span><?php endif; ?>
			</div>
			<div class="yui-u">
				<?php if ($ctx->hasSlot("utility_4")): ; ?><?php echo $ctx->getSlot("utility_4") ?><?php else: ; ?><span></span><?php endif; ?>
			</div>
		</div>
	<?php 
}

 ?><?php 
function tpl_1232078367_1_1_14vanillautie067bf7864cb5de95f90ad4b00c8340f_loader( $tpl, $ctx ) {
$tpl = clone $tpl ;
$ctx = $tpl->getContext() ;
$glb = $tpl->getGlobalContext() ;
$_translator = $tpl->getTranslator() ;
?>

	
	
	
	<?php ob_start(); ?>
		<?php echo phptal_escape(do_action('vanilla_before_utility_grid'), ENT_QUOTES, 'UTF-8');?>
		<?php $glb->utl_class = str_replace('gg','g', $ctx->vanilla['utility']); ?>
		<?php if ($ctx->vanilla['utility'] != 'yui-ga'): ; ?>
			<div id="utility" class="yui-d3 <?php echo phptal_escape($ctx->utl_class, ENT_QUOTES, 'UTF-8');?>">
				<?php 
if ($ctx->vanilla['utility'] == 'yui-gg'):  ;
/* 4 utility columns */ ;
endif ;
?>
				<?php if ($ctx->vanilla['utility'] != 'yui-gg'): ; ?>
					<div class="yui-u first">
						<?php if ($ctx->hasSlot("utility_1")): ; ?><?php echo $ctx->getSlot("utility_1") ?><?php else: ; ?><span></span><?php endif; ?>
					</div>
					<div class="yui-u">
						<?php if ($ctx->hasSlot("utility_2")): ; ?><?php echo $ctx->getSlot("utility_2") ?><?php else: ; ?><span></span><?php endif; ?>
					</div>
					<?php 
if ($ctx->vanilla['utility'] == 'yui-gb'):  ;
/* 3 utility columns */ ;
?>
						<div class="yui-u">
							<?php if ($ctx->hasSlot("utility_3")): ; ?><?php echo $ctx->getSlot("utility_3") ?><?php else: ; ?><span></span><?php endif; ?>
						</div>
					<?php endif; ?>
				<?php endif; ?>
			</div><!-- #utility -->
		<?php endif; ?>
		<?php echo phptal_escape(do_action('vanilla_after_utility_grid'), ENT_QUOTES, 'UTF-8');?>
	<?php $ctx->fillSlot("utility", ob_get_clean()); ?>

<?php 
}

 ?><?php 
function tpl_1232078367_1_1_14vanillautie067bf7864cb5de95f90ad4b00c8340f( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
$_translator = $tpl->getTranslator() ;
?>

<?php 
}

 ?><?php /* Generated by PHPTAL from /home/dynamicbt/www.dynamicbodytherapy.com/wp-content/themes/vanilla/blog-set/vanilla-utility.html */; ?>