<?php 
function tpl_1232078367_1_1_14homehtmla069a30ea8d48f95a9d337a7a6ee4e20_loader( $tpl, $ctx ) {
$tpl = clone $tpl ;
$ctx = $tpl->getContext() ;
$glb = $tpl->getGlobalContext() ;
$_translator = $tpl->getTranslator() ;
?>

<?php ob_start(); ?>
	<!-- hook: loop -->
	<?php 
$__repeat__ = $ctx->repeat ;
$__repeat__->entry = new PHPTAL_RepeatController(phptal_path($ctx->vanilla, 'entries')) ;
foreach ($__repeat__->entry as $__key__ => $ctx->entry ): ;
?>
		<?php if ($ctx->repeat->entry->number == '1'): ; ?>
			<?php 
$ctx = $tpl->pushContext() ;
$ctx->file = vanilla_get_template('content/' . $ctx->vanilla['content']['tpl_file']) ;
/* The content slot. */ ;
$ctx->pushSlots() ;
?><?php $tpl->executeMacro(''.$ctx->file.'/loader'); ?><?php 
$ctx->popSlots() ;
$ctx = $tpl->popContext() ;
?>
			<?php if ($ctx->hasSlot("content")): ; ?><?php echo $ctx->getSlot("content") ?><?php else: ; ?><span></span><?php endif; ?>
		<?php endif; ?>
	<?php endforeach; ?>
  
	<?php if ($ctx->hasSlot("content_middle")): ; ?><?php echo $ctx->getSlot("content_middle") ?><?php else: ; ?><span></span><?php endif; ?>
  
	<ol class="archive">
		<?php 
$__repeat__ = $ctx->repeat ;
$__repeat__->entry = new PHPTAL_RepeatController(phptal_path($ctx->vanilla, 'entries')) ;
foreach ($__repeat__->entry as $__key__ => $ctx->entry ): ;
?>
			<?php if ($ctx->repeat->entry->number > '1'): ; ?><li>
				<?php 
$ctx = $tpl->pushContext() ;
$ctx->file = vanilla_get_template('excerpt/' . $ctx->vanilla['excerpt']['tpl_file']) ;
/* The excerpt slot. */ ;
$ctx->pushSlots() ;
?><?php $tpl->executeMacro(''.$ctx->file.'/loader'); ?><?php 
$ctx->popSlots() ;
$ctx = $tpl->popContext() ;
?>
				<?php if ($ctx->hasSlot("excerpt")): ; ?><?php echo $ctx->getSlot("excerpt") ?><?php else: ; ?><span></span><?php endif; ?>
				<div id="post-content-<?php echo phptal_escape(phptal_path($ctx->entry, 'id', true), ENT_QUOTES, 'UTF-8');?>-target"></div>
			</li><?php endif; ?>
		<?php endforeach; ?>
	</ol><!-- .archive -->
<?php $ctx->fillSlot("loop", ob_get_clean()); ?>

<?php 
}

 ?><?php 
function tpl_1232078367_1_1_14homehtmla069a30ea8d48f95a9d337a7a6ee4e20( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
$_translator = $tpl->getTranslator() ;
?>

<?php 
}

 ?><?php /* Generated by PHPTAL from /home/dynamicbt/www.dynamicbodytherapy.com/wp-content/themes/vanilla/blog-set/loop/home.html */; ?>