<?php 
function tpl_1232078367_1_1_14contentdef49d5c6cc87e23416a5f3f72869d92303_loader( $tpl, $ctx ) {
$tpl = clone $tpl ;
$ctx = $tpl->getContext() ;
$glb = $tpl->getGlobalContext() ;
$_translator = $tpl->getTranslator() ;
?>

<?php ob_start(); ?>
	<div id="post-content-<?php echo phptal_escape(phptal_path($ctx->entry, 'id', true), ENT_QUOTES, 'UTF-8');?>" class="hentry full <?php echo phptal_escape(phptal_path($ctx->entry, 'class', true), ENT_QUOTES, 'UTF-8');?>">
		<h1 class="entry-title full-title"><a href="<?php echo phptal_escape(phptal_path($ctx->entry, 'permalink', true), ENT_QUOTES, 'UTF-8');?>" title="Permanent link to <?php echo phptal_escape(phptal_path($ctx->entry, 'title_attribute', true), ENT_QUOTES, 'UTF-8');?>" rel="bookmark" rev="post-<?php echo phptal_escape(phptal_path($ctx->entry, 'id', true), ENT_QUOTES, 'UTF-8');?>"><?php echo phptal_escape(phptal_path($ctx->entry, 'title', true), ENT_QUOTES, 'UTF-8');?></a></h1>
		<div class="entry-content full-content">
			<?php echo phptal_path($ctx->entry, 'content', true) ?>
			<?php if (phptal_path($ctx->entry, 'pages_link')): ; ?><p class="pages-link">Pages: <?php echo phptal_path($ctx->entry, 'pages_link', true) ?></p><?php endif; ?>
		</div><!--/entry-content-->
		<p class="filed">
			<?php if (phptal_path($ctx->entry, 'categories_list')): ; ?><span class="categories">Posted in <?php echo phptal_path($ctx->entry, 'categories_list', true) ?></span><?php endif; ?> 
			<?php if (phptal_path($ctx->entry, 'tags_list')): ; ?><span class="tags">Tagged with <?php echo phptal_path($ctx->entry, 'tags_list', true) ?></span><?php endif; ?>
		</p><!--/filed-->
		<?php if (phptal_path($ctx->entry, 'author')): ; ?><div class="by-line">
			<address class="author vcard full-author">
				<span class="by">By</span> <a class="url fn" href="<?php echo phptal_path($ctx->entry, 'author/link', true) ?>" title="View all posts by <?php echo phptal_escape(phptal_path($ctx->entry, 'author/name_attribute', true), ENT_QUOTES, 'UTF-8');?>"><?php echo phptal_escape(phptal_path($ctx->entry, 'author/name', true), ENT_QUOTES, 'UTF-8');?></a>
			</address>
			<span class="date full-date"><abbr class="published" title="<?php echo phptal_escape(phptal_path($ctx->entry, 'date_time', true), ENT_QUOTES, 'UTF-8');?>"><?php echo phptal_escape(phptal_path($ctx->entry, 'date', true), ENT_QUOTES, 'UTF-8');?></abbr></span>
		</div><?php endif; ?><!--/by-line-->
		<?php if (phptal_path($ctx->entry, 'comments_link')): ; ?><p class="comments-link"><?php echo phptal_path($ctx->entry, 'comments_link', true) ?></p><?php endif; ?>
		<div class="clear"></div>
		<div id="post-comments-<?php echo phptal_escape(phptal_path($ctx->entry, 'id', true), ENT_QUOTES, 'UTF-8');?>-target"></div>
		<?php if (phptal_path($ctx->entry, 'edit_link')): ; ?><div class="entry-editlink"><a href="<?php echo phptal_path($ctx->entry, 'edit_link', true) ?>"><?php echo phptal_escape(phptal_path($ctx->entry, 'edit_link_text', true), ENT_QUOTES, 'UTF-8');?></a></div><?php endif; ?>
	</div><!-- .post -->
<?php $ctx->fillSlot("content", ob_get_clean()); ?>

<?php 
}

 ?><?php 
function tpl_1232078367_1_1_14contentdef49d5c6cc87e23416a5f3f72869d92303( $tpl, $ctx ) {
$glb = $tpl->getGlobalContext() ;
$_translator = $tpl->getTranslator() ;
?>

<?php 
}

 ?><?php /* Generated by PHPTAL from /home/dynamicbt/www.dynamicbodytherapy.com/wp-content/themes/vanilla/blog-set/content/content-default.html */; ?>